### ISSUE TITLE
Import SDK inside Android application

### ISSUE THREAD

**Issue by Syna-One** [input-output-hk/atala-prism-wallet-sdk-kmm#103]
### Is this a regression?

No

### Description

Hello there!

I'm building an android application and I'm trying to import the sdk inside it but I don't succeed to do it.
It seems the package is protected 
```
Failed to resolve: io.iohk.atala.prism:walletsdk
Affected Modules: app
```
Inside your `build.gradle.kts`, I've found this:
```
maven {
            this.url = uri("https://maven.pkg.github.com/input-output-hk/atala-prism-apollo")
            credentials {
                this.username = System.getenv("ATALA_GITHUB_ACTOR")
                this.password = System.getenv("ATALA_GITHUB_TOKEN")
            }
        }
```

How could I get an ATALA github actor and token?

Thanks!

**Comment by Syna-One** [comment]
Hello! :)
Thanks for your answer (sorry for the delay)
Do you have any idea how much "not take long" is? Like few months, a year, two? :)
Is there a way to get access to IOHK organisation? (I guess nope)
Thanks for your answers :)

**Comment by hamada147** [comment]
Hello @Syna-One 👋,
Apollo repository has been made public and released to Maven Central.

The next step would be to update our the Wallet SDK to use the latest version which should happen in the next month after the Christmas break.

**Comment by goncalo-frade-iohk** [comment]
Hi @Syna-One! 

As my colleague @hamada147 pointed out it's already public including our other SDKs (TS and Swift) :) ! So it was just a month and a half to finish and make all the pipeline ready just in time for the festivities.

Closing this ticket now.
Any feedback please give it us since we are always looking for ways to enhance our work.

**Comment by SynaOne** [comment]
> Hello @Syna-One 👋, Apollo repository has been made public and released to Maven Central.
> 
> The next step would be to update the Wallet SDK to use the latest version of Apollo which should happen in the next month after the Christmas break.

Hey there! :)
Do you know why the KMM SDK is still unavailable on Maven Central? :)
Is there any issue, do you have a new ETA? 
Thanks!

**Comment by Syna-One** [comment]
> Hello @Syna-One 👋, Apollo repository has been made public and released to Maven Central.
> 
> The next step would be to update the Wallet SDK to use the latest version of Apollo which should happen in the next month after the Christmas break.

Hey there! :)
Do you know why the KMM SDK is still unavailable on Maven Central? :)
Is there any issue, do you have a new ETA?
Thanks!
