### ISSUE TITLE
ZKP presentation flow not working

### ISSUE THREAD

**Issue by mkbreuningIOHK** [input-output-hk/atala-prism-wallet-sdk-kmm#146]
### Is this a regression?

No

### Description

ZKP presentation flow is not working. It's following the same pattern as sdk-ts and sdk-swift but the presentation is failing.

- Checkout branch test/zkp-presentation-flow

- Open integration-test folder using terminal or IDE (`atala-prism-wallet-sdk-kmm/tests/end-to-end`)

   - Run `./gradlew clean test --tests "TestSuite" -Dcucumber.filter.tags="@proof and @anoncred"`

   - If debug needed you can see the run configuration in the attached image for Intellij IDEA

<img width="988" alt="image-20240328-202343" src="https://github.com/input-output-hk/atala-prism-wallet-sdk-kmm/assets/97112931/5dcfe856-7bf8-4dca-a177-d0267fbccab2">

### Please provide the environment you discovered this bug in

```true
OEA v1.31.0
Mediator 0.14.1
```

**Comment by cristianIOHK** [comment]
This issue was resolved and merged into main.
